# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
# patch the generated kubeadm config with some extra settings
apiServer:
  certSANs: [localhost, "127.0.0.1"]
# 1 control plane node and 1 worker
nodes:
- role: control-plane
- role: worker
